### ISSUE TITLE
Ottawa Building Footprint Import

### ISSUE THREAD

**Issue by DenisCarriere** [osmottawa/osm-changesets#6]
# Address Points

## Fix Manually
- [ ] [Garage bigger then house](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#19.74/45.39783/-75.71342)
- [ ] [Duplex with large shed +450](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#18.63/45.40379/-75.70047)
- [ ] [Multiple split parcels](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#19.75/45.40062/-75.68507)

## Warnings
- [x] [Large shed in the back](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#19.1/45.403/-75.687)
- [x] [Large sheds + house touching border](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#19.69/45.39918/-75.70051)
- [x] [Houses touching border of parcels](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#19/45.3903393/-75.6625028)
- [x] [Shed bigger than 450 sqft](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#19.5/45.39225/-75.72918)
- [x] [Two houses, same address, different parcel](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#18.92/45.39878/-75.69160)
- [x] [Use polylabel, Center of building isn't accurate](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#18.4/45.39931/-75.71261)
- [x] [Address center offset](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#18.52/45.26396/-75.56280)
- [x] [Address center offset](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#17.48/45.39914/-75.75350)
- [x] [Duplux large poly](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#19.81/45.39025/-75.69180)
- [x] [Center offset to void](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#17.48/45.39914/-75.75350)
- [x] [Center offset to void](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#18.25/45.34443/-75.72264)
- [x] [Very large distance placement > 500ft](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#16.32/45.36435/-75.73368)
- [x] [Centroid label not on buildling](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?fresh=true&title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ#19.22/45.34388/-75.72381)

## Errors

- [ ] [Land parcel needs to be dissolve, buildings overlap on two different parcels that are the same](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?fresh=true&title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ#16.67/45.36244/-75.73426)

## Nice to Have
- [ ] [Align Terraces with single address per parcel - Default to centroid of Parcel if no rules apply](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#19.61/45.40056/-75.68591)
- [ ] [Large rural parcels - apply custom rules](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#15.46/45.2416/-75.4961)
- [ ] [Align terrace homes](https://api.mapbox.com/styles/v1/pacgeo/ciye05lbc000m2smyb2b097w6.html?title=true&access_token=pk.eyJ1IjoicGFjZ2VvIiwiYSI6ImE2ZmE3YTQyNmRjNTVmYTAxMWE2YWZlNGFjZjMzZWVhIn0.wRU0txw3VIEOVtyc8PCYdQ&fresh#18.34/45.37400/-75.65532)

# Buildings

### `building=residential/house`
- [ ] greater than 3000 sqft (normally would be tagged as commercial)
- [ ] less than 600 sqft (could of be shed or garage)
- [ ] Also has an `addr:housenumber` + `addr:street` within 500m proximity (flag it as duplicate)
